#!/bin/bash
# This script inverts all images in the directory given to it as argument. The default directory is the current working directory.
# Script uses imagemagick

DIR=${1%/}
for file in ${DIR:-$PWD}/*; do
  EXT=${file##*.}
  echo -n $file
  if [[ $file == *_invert.$EXT  ]]; 
    then echo -e "\t---Already converted."
    else convert $file -negate ${file%$EXT}_invert.$EXT; echo ""
  fi
done
